// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhkmytrdyttpdzgiwycm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoa215dHJkeXR0cGR6Z2l3eWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjIzNzksImV4cCI6MjA2NTgzODM3OX0.0vcm8f-JSnd1bbDt2rTx3eaHJ_xC0_TO8sGE3Rv_w4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);